### PR TITLE
Sweep/SP fixes

### PR DESCRIPTION
**Pull request by bqpd**

### CODE REVIEW

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test this please

**Comment by bqpd** [comment]
@galbramc looks like this is correctly sending the unit tests to Jenkins, but not receiving any messages back from it? (the tests have all finished there)

I'll dig into this soon as I can, but have you seen this behaviour anywhere else?

**Comment by bqpd** [comment]
models: https://acdl.mit.edu/csi/view/convex%20engineering/job/CE_gpkit_PR_research_models/488/
unit: https://acdl.mit.edu/csi/view/convex%20engineering/job/CE_gpkit_PR_unit_tests/3160/
pylint: https://acdl.mit.edu/csi/view/convex%20engineering/job/CE_gpkit_PR_pylint/2397/
dependencies: https://acdl.mit.edu/csi/view/convex%20engineering/job/CE_gpkit_PR_dependencies/2350/

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
test gpkit please

**Comment by galbramc** [comment]
test gpkit please

**Comment by galbramc** [comment]
The Credentials under Source Code Management for every one of the jobs had been set back to "None". Most likely due to some Jenkins update.

**Comment by galbramc** [comment]
test models please

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
test models please

**Comment by whoburg** [comment]
@galbramc thanks for your help with this, you're a hero!

**Comment by galbramc** [comment]
@whoburg this is nothing. You are the one heading to the moon!

**Comment by bqpd** [comment]
> The Credentials under Source Code Management for every one of the jobs had been set back to "None". Most likely due to some Jenkins update.

Ha I saw the new interface, very modern.

Thanks for taking a look!

**Pull request merged**
