### PR TITLE
add reset_modelnumbers function

### LINKED ISSUE #1320: Issues diffing solutions of multiple instances of a model
I guess 'diffing' can have a lot of issues. 
If you run a model and save the solution, and then build another model and save the solution of that as well, the solutions have a different set of varkeys.
The first solution will have this varkey: 
```python
u_{8}_Engine/EnginePerformance/ThrustPerformance
```
And the second solution will have another: 
```python
u_{8}_Engine.1/EnginePerformance.1/ThrustPerformance.1
```
so that the intersection set of varkeys (```sol1vars.intersection(sol2vars)```) is empty. 
This seems problematic, because users may want to diff when a constraint is changed, which requires rebuilding the model.

### PR DESCRIPTION
**Pull request by bqpd**
Closes #1320 

@1ozturkbe, with this PR you can now compare solutions created in the same session by resetting modelnumbers in between with `gpkit.reset_modelnumbers()`

### CODE REVIEW

**Comment by bqpd** [comment]
test models please

**Comment by 1ozturkbe** [comment]
neat, although it still looks like a hack to me. Can you remind me why we have different numbers in the first place?

**Comment by bqpd** [comment]
let's chat about it tomorrow!

**Comment by 1ozturkbe** [comment]
great!

**Pull request merged**
