### PR TITLE
try additional file removal strategy

### PR DESCRIPTION
**Pull request by bqpd**

### CODE REVIEW

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
I still see temporary files lingering. I saw a number of temporary directories created and deleted, but not all got deleted. The directories that remain have gpkit_mosek and gpkit_mosek.sol files in them.

**Comment by galbramc** [comment]
Maybe you need some while loop to check if the file still lingers.

**Comment by bqpd** [comment]
huh, they should all be getting deleted: either by os.remove or by
shutil.rmtree! Even weirder that some are and some are not deleted.

One (kinda silly) alternative could be to reuse the same temporary filename
for each session of gpkit, which should work but also creates an entirely
unnecessary potential race condition.

**Comment by bqpd** [comment]
There is a while loop in the rmtree function! If all remaining directories
also have files leftover, that implies os.remove isn't doing anything, so
this PR isn' necessary.

**Comment by galbramc** [comment]
Welcome to the world of windoze. I'm guessing Windoze is locking the file claiming it is still in use when you are trying to remove it. Humor me and put a while exists in front of each remove command.

**Comment by bqpd** [comment]
done! added while loop

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
You missed the '.path.'. Should be:
```
os.path.isfile(filename)
```

**Comment by bqpd** [comment]
derp

**Comment by galbramc** [comment]
Nope... try this:

```
try:
    shutil.rmtree(path)
except OSError as e:
    # Reraise unless ENOENT: No such file or directory
    # (ok if directory has already been deleted)
    if e.errno != errno.ENOENT:
        raise
```

**Comment by bqpd** [comment]
Heh, wrapped it around my existing recursion; how's that?

>

**Comment by galbramc** [comment]
Geez! I don't know why some still linger... For all these incarnations there are fewer left behind, there are still ~5-10 that don't get deleted.

**Comment by galbramc** [comment]
Oh wait. Wrong PR building.

**Comment by galbramc** [comment]
Try removing the extra arguments to shutil.rmtree.

**Comment by bqpd** [comment]
done! :| thanks so much for like...watching the temporary files directory

**Comment by galbramc** [comment]
I don't understand this... There are still files lingering, but it is better than what it was without any of these changes. Maybe the while should be on the directory instead of the file inside?

**Comment by bqpd** [comment]
heh. giving that a try...

**Pull request closed without merging**
