### PR TITLE
deduplicate gp hmaps

### LINKED ISSUE #1551: Redundant equality constraint causes issues with CVXOPT
When using CVXOPT, a redundant equality constraint will fail to solve and send the model into debug mode (see the example below). The model is feasible as demonstrated by the successful solve on the first go. Once in debug mode, the model is solved successfully with relaxed constraints but shows 0% relaxation.

As far as I have tried, redundant inequality constraints do not seem to have this issue.

Thoughts?

## Environment Information
- Python: 3.7.0
- GPkit: 0.9.9.9.1
- CVXOPT: 1.2.6

## Test model
```python
from gpkit import Model, Variable

a = Variable('a', 1)
b = Variable('b')
c = Variable('c', 2)
d = Variable('d')
z = Variable('z', 0.5)

# create a simple GP with equality constraints
const = [
    z == b/a,
    z == d/c,
]

# simple cost
cost = a + b + c + d

# create a model
m = Model(cost, const)

# solve the first version of the model (solves successfully)
m.solve(solver='cvxopt')

# add a redundant equality constraint
m.extend([
    z == b/a
])

# solver will fail and attempt to debug
m.solve(solver='cvxopt')
```

### Example Output
```
Using solver 'cvxopt'
 for 2 free variables
  in 5 posynomial inequalities.
Solving took 0.00302 seconds.
Using solver 'cvxopt'
 for 2 free variables
  in 7 posynomial inequalities.
Solving took 0.00111 seconds.
The model ran to an infinitely low cost; bounding the right variables would prevent this.
Since this model solved in less than a second, let's run `.debug()` automatically to check.
`
< DEBUGGING >
> Trying with bounded variables and relaxed constants:
>> Failure.
> Trying with relaxed constraints:
Solves with these constraints relaxed:
   0:    0% relaxed, from z = b/a 
                     to z <= a^-1·b 
>> Success!
```

### PR DESCRIPTION
**Pull request by bqpd**
Closes #1551

### CODE REVIEW

**Comment by bqpd** [comment]
test models please

**Comment by galbramc** [comment]
test gpkit please

**Comment by galbramc** [comment]
test gpkit please

**Comment by galbramc** [comment]
test gpkit please

**Comment by galbramc** [comment]
@bqpd Can you replace msg-template in the .pylintrc file with this:

msg-template={path}:{module}:{line}: [{msg_id}({symbol}), {obj}] {msg}

**Comment by bqpd** [comment]
@galbramc done!

**Comment by galbramc** [comment]
Ok, I need to upgrade renyolds to Ubuntu 20.04, and then all of this should be working again.

**Comment by galbramc** [comment]
test gpkit please

**Comment by galbramc** [comment]
You can work on fixing the pylint warnings in the mean time...

**Comment by bqpd** [comment]
ooh new pylint

**Comment by galbramc** [comment]
Maybe, the Jenkins pylint configurations had gotten lost during some jenkins updates, and we were not actually catching any of the pylint warnings. So we had false green pylint results.

**Pull request merged**
