### PR TITLE
warn early of obvious dual infeasibility

### LINKED ISSUE #1224: don't solve if there's an obvious dual infeasibility error
because we might as well warn early!

### PR DESCRIPTION
**Pull request by bqpd**
Closes #1224

### CODE REVIEW

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
@mjburton11 this branch is pointing out that there's no fuel-weight to fuselage volume constraint in gassolar/gas/gas.py !!

**Comment by mjburton11** [comment]
Ok testing now in convexengineering/gassolar#25.  It's very strange that this didn't fail `gassolar` ealier.  I modified `elliptical_fuselage.py` recently to not take a variable arg in setup and so I should have seen it fail during testing... might have happened before we fixed the issue with the branches.

**Comment by bqpd** [comment]
Yeah I'm pretty excited about integrating more automatic analysis of the A matrix before solving, it seems to only be pointing out good things (this and an unused variable in turbofan)

**Comment by mjburton11** [comment]
Nice! Seems like an extremely useful feature to have

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Pull request merged**
