### PR TITLE
Check dual infeasibility on build

### PR DESCRIPTION
**Pull request by bqpd**
check out `performance_modeling.py` for an example of what this looks like

### CODE REVIEW

**Comment by bqpd** [comment]
@mjburton11, check https://github.com/convexengineering/gpkit/pull/1238/files#diff-7674edf32f132d51737e3fb5ada5d83d out!

**Comment by mjburton11** [comment]
Most of the wing models now have unbounded variables listed in the doc string.  Maybe good test case for this! convexengineering/gplibrary@86df0bfa83a3df680a50edc90b441bad66a00c9b

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
I pushed to the branch!

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
this should work on all model tests except for the gplibrary ones...

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
model tests are now failing only on gplibrary; this is ready to merge!

**Comment by bqpd** [comment]
@pgkirsch @mjburton11 @1ozturkbe check out the syntax in gplibrary; any concerns before this gets merged?

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
note to self: create "variables pop on use" PR after this is merged

**Pull request merged**
