### PR TITLE
Making minimal Sankey diagram for solar.

### LINKED ISSUE #1314: Add to documentation that Sankey only works in iPython notebooks.
Firstly, the syntax must be changed, because the Solar code syntax has changed. 
```python
    SP = True
    Vehicle = Aircraft(Npod=3, sp=SP)
    M = Mission(Vehicle, latitude=[20])
    M.cost = M[M.aircraft.Wtotal]
    from gpkit.interactive.sankey import Sankey
    Sankey(M).diagram(M.solar.Wtotal)
```

### PR DESCRIPTION
**Pull request by 1ozturkbe**
closes #1314

@bqpd just decided to make a PR with the required changes. One step remains: how do you save an svg from the SankeyWidget, so we can update the picture? I have been trying to figure this out and failing. Lmk.

### CODE REVIEW

**Comment by bqpd** [comment]
Nice, that's lovely!

**Comment by bqpd** [comment]
Could you update the svg in that directory as well?

**Comment by bqpd** [comment]
(use the browser inspector to grab the svg element, copy-past into the text document...or I can do it)

**Comment by 1ozturkbe** [comment]
I'll take care of it. Thanks!

**Comment by bqpd** [comment]
What actually...the SVG attached doesn't have the right unicode for the line labels...(a, b, etc)

**Comment by bqpd** [comment]
You can see the preview on github with `?`s instead of the labels...

**Comment by 1ozturkbe** [comment]
Interesting... I checked that I could load in chrome but I didn't see the error, my b. I don't know why that is the case, but I'll check it.

Also, I've been generating the Sankey plots for solar and I get results that are not insightful (there are just too many constraints, and the Sankey diagrams look somewhat incoherent). Maybe we need to switch to a dumber model.

**Comment by 1ozturkbe** [comment]
@bqpd it would be great to have a way to test the code included in the GPkit documentation once in a while. None of the plots in the Sankey docs can be recreated using the code in the docs. Immensely frustrating.

**Comment by bqpd** [comment]
Yeah there's an issue open for interactives testing...Sankey will present
an especial difficulty :-/ I could add it to the new-version checklist?

**Comment by bqpd** [comment]
Maybe add the solar commit you're using to the docs just to ensure
reproducibility?

**Comment by 1ozturkbe** [comment]
Unless @mjburton11 wants to fix the code in the Sankey documentation, I may actually merge all of my thesis code into gplibrary, and make Sankey diagrams with those. The Sankey diagrams of Solar are overly complicated and don't provide much intuition.

**Comment by 1ozturkbe** [comment]
I'm using latest of master on solar.

**Comment by bqpd** [comment]
master is a moving target though, so we should refer to an explicit commit
and update it periodically. Feel free to create the gplibrary PR!

**Comment by 1ozturkbe** [comment]
You're right... Honestly I think it's probably better to make a gpkitdocs branch within solar or whatever so we can refer to the branch itself.

**Comment by bqpd** [comment]
Yeah that sounds like a better idea!

**Comment by bqpd** [comment]
@1ozturkbe wanna update the last two svgs and I'll make the branch?

**Comment by 1ozturkbe** [comment]
alright... let me figure this out.

**Comment by 1ozturkbe** [comment]
Also, Sankey diagrams make iPython crash like no other. It's pissing me off.

**Comment by bqpd** [comment]
is it the really big ones? or maybe updating ipython notebook would fix it?

**Comment by 1ozturkbe** [comment]
I can't update the one with aircraft span (M.aircraft.b), but I have created a branch within solar called gpkitdocs with the notebook so you can update it if you'd like. Because I gave up trying to generate that plot; even fully updated my Chrome cannot handle it. Otherwise this is ready to go.

**Comment by 1ozturkbe** [comment]
Damn it, this is precisely why the model numbering is annoying. If I ever do this for not my own models on my own volition, pinch me.

**Comment by 1ozturkbe** [comment]
Updated all. Merge when ready @bqpd.

**Pull request merged**
