### PR TITLE
Speed up subinplace

### PR DESCRIPTION
**Pull request by bqpd**

### CODE REVIEW

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
@galbramc looks like there's some fun with a new pylint version, huh.

**Comment by bqpd** [comment]
@galbramc also, Jenkin's MOSEK license seems to have expired?

**Comment by bqpd** [comment]
And some of the outputs from cvxopt have changed on Jenkins, most notably on `autosweep.py` ... :(

**Comment by bqpd** [comment]
Yup, the output changes are all numpy. todo:
  - [ ] new MOSEK license?
  - [ ] updated pylintrc

**Comment by bqpd** [comment]
Windows 10 CVXOPT has this error, as well:  `unable to access 'https://github.com/convexengineering/gpkit/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version`

**Comment by bqpd** [comment]
macys_VM is failing pylint with `can't open file '/Users/jenkins/mosek/8/tools/platform/osx64x86/python/2/setup.py': [Errno 2] No such file or directory`

**Comment by bqpd** [comment]
@galbramc summary of jenkins issues above

**Comment by galbramc** [comment]
Woody procured the previous MOSEK license. I can fix everything else...

**Comment by galbramc** [comment]
test gpkit please

**Comment by galbramc** [comment]
test gpkit please

**Comment by galbramc** [comment]
I'm traveling, and I can't do much about the Windows 7 VM until I get back next week.

**Comment by bqpd** [comment]
ah no worries! Should I email you the new MOSEK license?

**Comment by galbramc** [comment]
test gpkit please

**Comment by bqpd** [comment]
test gpkit please

**Comment by bqpd** [comment]
test models please

**Comment by galbramc** [comment]
I can't update the license on windoze until monday...

**Comment by bqpd** [comment]
@galbramc thanks a bunch, enjoy your travels!

**Comment by bqpd** [comment]
oh, and macysVM just failed on models testing with `python: can't open file '/Users/jenkins/mosek/8/tools/platform/osx64x86/python/2/setup.py': [Errno 2] No such file or directory`

**Comment by galbramc** [comment]
so I switched things around. The VM is now El Capitain 10.11, and macys is High Sierra 10.13. So I put mosek 8 on macys instead. So all the scripts that say 

```
elif [[ $buildnode == *macys* ]]; then
  if [[ $optimizer == mosek ]]; then
    if [[ $buildnode == macys_VM ]]; then
```

need to be changed to

```
elif [[ $buildnode == *macys* ]]; then
  if [[ $optimizer == mosek ]]; then
    if [[ $buildnode == macys ]]; then
```

Could you do that as you discover ones that I missed?

**Comment by galbramc** [comment]
test models please

**Comment by galbramc** [comment]
any thoughts on gpkit install issues? Seems like the fact that the venv is mounted on /jenkins rather than /home/jenkins is causing problems.

**Comment by galbramc** [comment]
test gpkit please

**Comment by galbramc** [comment]
test gpkit please

**Comment by galbramc** [comment]
test gpkit please

**Comment by galbramc** [comment]
test gpkit please

**Comment by galbramc** [comment]
the windows 7 bug was git being too old. I installed a newer version and it started working again.

test models please

**Comment by bqpd** [comment]
awesome, thanks a bunch for getting jenkins back up! weird about the git version being an issue...

**Pull request merged**
