### PR TITLE
fix sankey diagrams

### PR DESCRIPTION
**Pull request by bqpd**
@danielhfourie @pgkirsch 

 To do:
  - [x] add ipysankeywidget to Jenkins
  - [x] deduplicate `constrlinks` and `varlinks`
  - [x] regenerate documentation examples
  - [x] include fixed-variable sensitivities as if they were equality constraints in the models they're created in
  - [x] document maxdepth, constraints, constraintlabels, going lower down
  - [x] add objective to relevant variable sensitivities
  - [x] interactive zoom?
  - [ ] include identical variables (those in tight `var1 <= var2` or `var1 == var2` constraints)
  - [x] fix the attometer bug in python 3.7+

### CODE REVIEW

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
@pgkirsch @danielhfourie this is now merged! check https://gpkit.readthedocs.io/en/latest/visint.html for the new syntax and interactive usage, and let me know if anything's unclear :D

**Comment by danielhfourie** [comment]
looks lovely! documentation and syntax makes sense. However when I test your WGS\ sankeys.ipynb on my machine, the model solves, and Sankey() runs without error, but no diagram shows up - just blank output. I'm running the latest gpkit master branch, ipysankeywidget 0.3.0, python 3.7.4.  I'll poke around to see what else I can find.

**Comment by bqpd** [comment]
ohh you need to activate the extension: run

```
$ jupyter nbextension enable --py --sys-prefix widgetsnbextension
$ jupyter nbextension enable --py --sys-prefix ipysankeywidget
```

**Comment by bqpd** [comment]
added the notes above to the documentation!

**Pull request merged**
