### PR TITLE
account for SignomialEqualities in SPData

### PR DESCRIPTION
**Pull request by bqpd**
@whoburg, ready for review

### CODE REVIEW

**Comment by galbramc** [comment]
test gpkit please

Fixing the dependency tests.

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by galbramc** [comment]
tests gpkit please

**Comment by galbramc** [comment]
test gpkit please

**Pull request closed without merging**
