### PR TITLE
values 'pop' after first use

### LINKED ISSUE #1175: values clobbering new substitutions because of constraint ordering choice
Looking at commit convexengineering/solar@e99e9e7428911d6f769684d1d7cc0b38939283b0 in solar, solving `solar.py` and convexengineering/library@c6da5c00e87137a7af7e32dcff2dc141e612eea5 in gpkitmodels.  I am subbing in tau in HTail.  

```python 
class HorizontalTail(AeroSurf):
    "horizontal tail model"
    flight_model = TailAero
    sparModel = None

    def setup(self, N=3, lam=0.8):
        self.ascs = AeroSurf.setup(self, N, lam)
        self.planform.substitutions.update({"AR": 4, "\\tau": 0.08})
```
But when I solve the model I get this:
```python
In [2]: sol("\\tau")
Out[2]: 
{\tau_Mission/Aircraft/Empennage/HorizontalTail/Planform: 0.115,
 \tau_Mission/Aircraft/Empennage/VerticalTail/Planform.1: 0.115,
 \tau_Mission/Aircraft/AeroSurf/Planform.2: 0.115}

In [3]: M.substitutions["\\tau_Mission/Aircraft/Empennage/VerticalTail/Planform.
   ...: 1"]
Out[3]: 0.115

In [4]: sol("AR")
Out[4]: 
{AR_Mission/Aircraft/Empennage/HorizontalTail/Planform: 4,
 AR_Mission/Aircraft/Empennage/VerticalTail/Planform.1: 3.7197870897370509,
 AR_Mission/Aircraft/AeroSurf/Planform.2: 26.66897625889953}
```
Pretty weird that `AR` got changed, but not `tau`

### LINKED ISSUE #1232: can't delete substitutions within model
I'm trying to the following in `solar`

```python
  class Aircraft(Model):
      "vehicle"
      fuseModel = None
      def setup(self, sp=False):
  
          self.wing = WingGP()
          del self.wing.substitutions["\\tau"]
```
 but it won't delete the substitution.   If I delete it after creating mission, it will delete.  Is this behavior intended?

### PR DESCRIPTION
**Pull request by bqpd**
Closes #1232
Closes #1175

### CODE REVIEW

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
ugh this breaks a lot of the model tests :p @mjburton11 is this a bad idea?

**Comment by mjburton11** [comment]
Hmmm it might be.  I can argue it both ways, but I'm leaning towards not implementing this.  My thoughts on this are: the submodels should be designed with maximum flexibility.  A user can fix a variable to get a solution to run.  But he should never have to delete a substitution.  Let's talk more on Monday.

**Comment by bqpd** [comment]
Sounds good :)

**Comment by bqpd** [comment]
test models please

**Comment by mjburton11** [comment]
what's the status on this PR?

**Comment by bqpd** [comment]
Still planned, but it breaks model checks and so will require some slogging

**Comment by bqpd** [comment]
Closing this because there'll be a much easier implementation of the idea after #1238 is merged

**Pull request closed without merging**
