### PR TITLE
add SolSavingEnvironment, halving pickle size

### PR DESCRIPTION
**Pull request by bqpd**
Per #1497

@pgkirsch this halves pickle size without removing any solution information. Between this and the compression I'd expect that 110MB file to drop to less than 10MB.

### CODE REVIEW

**Comment by bqpd** [comment]
test models please

**Comment by pgkirsch** [comment]
@bqpd just curious: what do the "construction/solve attributes" allow you to do with an already-computed solution? Re-solve without needing the original model object?

**Comment by bqpd** [comment]
The following attributes are removed: `["mfm", "pmap", "bounded", "meq_bounded", "v_ss", "unsubbed", "varkeys"]`.

`mfm`: maps how monomials simplified during substitution so that sensitivities can be properly mapped back
`pmap`: maps how the constant term (if any) was taken to the `<= 1` side and divided out
`bounded`: which variables were upper or lower bounded by this constraint at its creation
`meq_bounded`: which variables were conditionally upper or lower bounded through a monomial equality
`v_ss`: the individual variable sensitivities in each constraint
`unsubbed`: the presubstitution polynomial representations of the constraint
`varkeys`: the varkeys in the constraint

All of these except for `v_ss` are recreatable by initing a new constraint with the left, oper, and right of the original.

**Comment by pgkirsch** [comment]
Ah awesome, thanks for the detailed explanation!

**Pull request merged**
