### PR TITLE
Putting relaxed constants solve into algorithms

### PR DESCRIPTION
**Pull request by 1ozturkbe**
Not ready, but will be.

### CODE REVIEW

**Comment by 1ozturkbe** [comment]
learning how to create autodocs...

**Comment by 1ozturkbe** [comment]
test models please

**Comment by 1ozturkbe** [comment]
@bqpd once the tests complete (pretty sure they will pass), feel free to review and merge.

**Comment by 1ozturkbe** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
Looks good! To be merged I think this needs
  1. to be reformulated as a ConstraintSet or Model
  2. test of example usage
  3. documentation of that example

**Comment by 1ozturkbe** [comment]
Alright... I guess this is how we increase the truck number. Will keep you updated.

**Comment by 1ozturkbe** [comment]
Btw, do you think that relaxed_constants should be a method of Model then? or should there be a class RelaxedModel(Model)?

**Comment by 1ozturkbe** [comment]
I will just make a RelaxedModel class, which makes it easy to use ConstantsRelaxed and ConstraintsRelaxed.

**Comment by bqpd** [comment]
I'd probably make a RelaxedSPModel or something for this particular usecase
with these particular process_results

**Comment by 1ozturkbe** [comment]
@galbramc can you explain why the unit tests are failing on three machines with actual failures? I am quite confused.

**Comment by 1ozturkbe** [comment]
Here's the final message: 
 Cost
+ exit 1
Build step 'Conditional step (single)' marked build as failure
[Cobertura] Publishing Cobertura coverage report...

[Cobertura] Publishing Cobertura coverage results...

[Cobertura] Cobertura coverage report found.

INFO: Starting to record.
INFO: Processing JUnit
INFO: [JUnit] - 30 test report file(s) were found with the pattern 'test_reports/*.xml, test_reports_nounits/*.xml' relative to '/jenkins/workspace/gpkit_PullRequest_Unit/cvxopt' for the testing framework 'JUnit'.
INFO: Check 'Failed Tests' threshold.
INFO: Check 'Skipped Tests' threshold.
INFO: Setting the build status to FAILURE
INFO: Stopping recording.
[WS-CLEANUP] Deleting project workspace...[WS-CLEANUP] done
Finished: FAILURE

**Comment by galbramc** [comment]
You are looking at the wrong place. A good tip is to look at the "Parsed Console Output" (https://acdl.mit.edu/csi/job/gpkit_PullRequest_Unit/buildnode=reynolds,optimizer=cvxopt/2559/parsed_console/). Your changes are modifying the examples in the documentation. @whoburg considered this to be a failure as the source no longer matches the documentation. You should talk with @bqpd in regards to if you need to fix your code or update the documentation.

**Comment by 1ozturkbe** [comment]
Thanks @galbramc, these are things I was not told. I think I can sort this out, sorry about the noob questions.

**Comment by 1ozturkbe** [comment]
@bqpd I have thought again about this, and perhaps it is better that we put this into localsolve. We can have a trigger (relaxed_constants = True) that can be defaulted to False. This way we can integrate these methods more seamlessly into the SP algorithm. Thoughts?

**Comment by bqpd** [comment]
I think this became PCCPsolve, yeah? Check the Python3.5 PR, I make replaced localsolve with this!

**Pull request closed without merging**
