### PR TITLE
Partial vector substitution

### PR DESCRIPTION
**Pull request by bqpd**
allows substitutions like ```m.substitutions[v[0,2:]] = 1  # or np.ones(v[0,2:].shape)```

### CODE REVIEW

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
@pgkirsch what do you think of this feature's utility? It seems to me like something that should Just Work, so I'm willing to take the performance hit.

**Comment by pgkirsch** [comment]
@bqpd that seems helpful! This seems like it would further simplify the proposed aero changes?

I assume that syntax carries over to the setup method form?
```python
def setup(self):
...
    substitutions = {
        v[0,2:]: 1,
    ...
    }

    return constraints, substitutions
```

I know I'm sort of pushing the envelope on some of these vector variable subs, but do you have other users with anything similar in use case?

**Comment by bqpd** [comment]
yup, carries over!

I think this is one of those things where people might have tried to use it, it didn't work, they found an alternative without mentioning...

**Comment by pgkirsch** [comment]
Awesome!

Have you profiled what the performance hit is for a large model? I can't imagine it's too significant, right?

**Comment by bqpd** [comment]
it was ~4% of the time in that function...don't remember exactly the timing
in my test run, but no more than a couple hundredths of a second.

>

**Comment by pgkirsch** [comment]
Seems very tolerable!

**Comment by bqpd** [comment]
I'm just so used to making things quicker when I make changes to core classes :p

**Comment by pgkirsch** [comment]
Ha sorry!

**Comment by bqpd** [comment]
test models please

**Pull request merged**
