### PR TITLE
don't transmute sig ineqs when they become posy

### LINKED ISSUE #1184: test sweeps + Tight
- [x] test sweeps + Tight https://github.com/convexengineering/gpkit/issues/911
- [x] it'd be great if the results were united but still scalar before process_results https://github.com/convexengineering/gpkit/issues/860
- [x] debug should skip processing results https://github.com/convexengineering/gpkit/issues/1173 (kinda fixed: see #1220)

### LINKED ISSUE #1206: calculate derivatives of linked variables!
this'll give us better sensitivities :D

### LINKED ISSUE #1245: Sweep only solves if solved as a point solution first
I have an SP (@1ozturkbe's SimPleAC model) that I'm using for my scitech paper. I am trying to substitute in the only variables in an SP to make it a GP and run a sweep. However, the sweep only works if I do a point solution first. Super weird and I'm not sure what's going on.

Works:
```python
In [1]: from SimPleAC import SimPleAC
impor
In [2]: import numpy as np

In [3]: sa = SimPleAC()

In [4]: sa.substitutions.update({'V_f_wing': 0.5, 'V_f_fuse': 0.5})

In [5]: sol = sa.solve()
Using solver 'mosek'
Solving for 18 variables.
Solving took 0.0192 seconds.

In [6]: sa.substitutions.update({'V_f_wing': ('sweep', np.linspace(0.1, 0.5, 3)), 'V_f_fuse': ('sweep', np.linspace(0.1, 0.5, 3))})

In [7]: sol = sa.solve(skipsweepfailures=True)
Solving over 9 passes.
Sweeping took 0.286 seconds.

In [8]: sol['cost']
Out[8]: 
<Quantity([ 3692.02620323  4149.66230067  4628.21398783  5090.75254533  5742.44314406
  6226.59922411  6021.89573896  6816.06094291  7362.77152096], 'newton')>
```

Doesn't work:
```python
In [1]: from SimPleAC import SimPleAC
im
In [2]: import numpy as np

In [3]: sa = SimPleAC()

In [4]: sa.substitutions.update({'V_f_wing': ('sweep', np.linspace(0.1, 0.5, 3)), 'V_f_fuse': ('sweep', np.linspace(0.1, 0.5, 3))})

In [5]: sol = sa.solve(skipsweepfailures=True)
Solving over 9 passes.
---------------------------------------------------------------------------
RuntimeWarning                            Traceback (most recent call last)
<ipython-input-5-dd498f18cae5> in <module>()
----> 1 sol = sa.solve(skipsweepfailures=True)

/Users/philippekirschen/Documents/MIT/Research/GPkit/gpkit/gpkit/constraints/prog_factories.pyc in solvefn(self, solver, verbosity, skipsweepfailures, *args, **kwargs)
     75             run_sweep(genfunction, self, solution, skipsweepfailures,
     76                       constants, sweep, linked,
---> 77                       solver, verbosity, *args, **kwargs)
     78         else:
     79             self.program, progsolve = genfunction(self)

/Users/philippekirschen/Documents/MIT/Research/GPkit/gpkit/gpkit/constraints/prog_factories.pyc in run_sweep(genfunction, self, solution, skipsweepfailures, constants, sweep, linked, solver, verbosity, *args, **kwargs)
    138 
    139     if not solution:
--> 140         raise RuntimeWarning("no sweeps solved successfully.")
    141 
    142     solution["sweepvariables"] = KeyDict()

RuntimeWarning: no sweeps solved successfully.
```

### PR DESCRIPTION
**Pull request by bqpd**
Closes #1245
Closes #1184 
Closes #1206

### CODE REVIEW

**Comment by bqpd** [comment]
test this please

**Comment by bqpd** [comment]
retest this please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
@mjburton11 this has a fun (if pretty mild) effect on the gplibrary models; eta and lam acquire (reasonably large, +0.5 to +0.7) sensitivities that they previously lacked, at least on jho!

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test this please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test this please

**Comment by bqpd** [comment]
TODO: use t_night/t_day to check that the sensitivities returned are actually correct.

**Comment by bqpd** [comment]
test this please

**Comment by bqpd** [comment]
test models please

**Comment by mjburton11** [comment]
@bqpd that's really cool!

**Pull request merged**
