### PR TITLE
Appropriate verbosity check for 'SP not converging' warning. 

### PR DESCRIPTION
**Pull request by 1ozturkbe**
Pretty straightforward really. This warning really shouldn't pop up if verbosity=0.

### CODE REVIEW

**Comment by 1ozturkbe** [comment]
test this please

**Comment by 1ozturkbe** [comment]
Oy Jenkins is going haywire. Let me see what is going on, because everything works locally.

**Comment by 1ozturkbe** [comment]
Oy, here's the message..

+ virtualenv /jenkins/workspace/CE_gpkit '(PR' unit 'tests)/cvxopt/venv2_gpkit'
There must be only one argument: DEST_DIR (you gave /jenkins/workspace/CE_gpkit (PR unit tests)/cvxopt/venv2_gpkit)
Usage: virtualenv [OPTIONS] DEST_DIR

Ummm, I don't yet have a Jenkins user, so can you help @bqpd?

**Comment by bqpd** [comment]
test this please

**Comment by bqpd** [comment]
@galbramc, did the virtualenv version update?

**Comment by bqpd** [comment]
oh, nope, it's because I used a space in the new naming scheme. fixing!

**Comment by bqpd** [comment]
test this please

**Comment by bqpd** [comment]
@1ozturkbe seems to be fixed

**Comment by 1ozturkbe** [comment]
Looks great. Merging.

**Pull request merged**
