### PR TITLE
Clean breakdowns

### PR DESCRIPTION
**Pull request by bqpd**

### CODE REVIEW

**Comment by bqpd** [comment]
test models please

**Comment by galbramc** [comment]
Looks like the unit test take over an hour to run with this change...

**Comment by bqpd** [comment]
i don't think they're hanging on the change though, and it's only on macys

**Comment by galbramc** [comment]
Strange, I added a timer to the example execution. It definitely seems to be the examples that take a long time now.

**Comment by bqpd** [comment]
oh dang I'll double check

**Comment by galbramc** [comment]
I fixed the Windoze batch files, now we have a legit error (but strange) on Windoze as well.

**Pull request merged**
