### PR TITLE
Revert "coverage"

### PR DESCRIPTION
**Pull request by bqpd**
Reverts convexengineering/gpkit#1505

testing if this last PR was causing the `test_table_diff` failures

### CODE REVIEW

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
@1ozturkbe from the above it looks like those table_diff errors are caused by the recent commit, but I still can't reproduce it on this end!

**Comment by bqpd** [comment]
test models please

**Comment by 1ozturkbe** [comment]
Glad this was resolved! Thanks though @bqpd for checking if this was breaking robust!

**Comment by bqpd** [comment]
sure thing!

>

**Pull request closed without merging**
