### PR TITLE
added copy model classes

### PR DESCRIPTION
**Pull request by alisaab**
I added two new classes under gpkit.Model: the first copies a model with  its original substitutions only while flattening constraints,  while the second copies a models with all its substitutions while preserving hierarchy.

### CODE REVIEW

**Comment by bqpd** [comment]
add to whitelist

**Comment by bqpd** [comment]
test this please

**Comment by bqpd** [comment]
test models please

**Comment by 1ozturkbe** [comment]
Looks OK, but needs to also work for signomials. Let me look into this.

**Comment by alisaab** [comment]
EqualModel works for signomials. I was thinking that we might only need EqualModel, maybe with a different name. SameModel might not be of much importance. what do you think ? @1ozturkbe

**Comment by 1ozturkbe** [comment]
Sorry this slipped under my radar. If we are only adding EqualModel, it's probably better to not go ahead with this pull request, and users can figure it out on their own that you can have more of the same model by calling Model(m.cost, m.substitutions) etc.

**Comment by 1ozturkbe** [comment]
@alisaab thoughts?

**Comment by alisaab** [comment]
yes sure, this can be replaced by Model(m.cost, m.flat(constraintsets=False), m.substitutions). No need for the EqualModel if this is straight forward for the users. @1ozturkbe

**Comment by 1ozturkbe** [comment]
Aight, closing then!

**Pull request closed without merging**
