### PR TITLE
pylint

### PR DESCRIPTION
**Pull request by whoburg**
fixes tab/spaces error introduced by #1168

### CODE REVIEW

**Comment by whoburg** [comment]
test this please

**Comment by whoburg** [comment]
@galbramc, we moved the gpkit repo and tests no longer trigger for me when I open a PR (I had to ask Jenkins nicely). Any chance there is an easy config setting to make the testing trigger automatically for whitelisted users?

**Comment by whoburg** [comment]
test models please

**Comment by whoburg** [comment]
@bqpd can you please make me an owner

**Comment by bqpd** [comment]
Oops yes. I think because I invited you on group creation I needed you to accept the invite first

**Comment by bqpd** [comment]
done!

**Comment by galbramc** [comment]
@whoburg, I apparently accidentally removed you from the jenkins admin list on a couple of PR setups in jenkins when we moved over the repo. I've added you back in now and hopefully the PRs should trigger builds automatically again.

Shouldn't you be working on going to space?

**Pull request closed without merging**
