### PR TITLE
miscellaneous speedups and fixes

### PR DESCRIPTION
**Pull request by bqpd**

### CODE REVIEW

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
@galbramc, windows couldn't find gcc for some reason? https://acdl.mit.edu/csi/job/gpkit_PullRequest_Models/272/buildnode=windows10x64,optimizer=mosek/console

**Comment by bqpd** [comment]
test models please

**Comment by galbramc** [comment]
this script was out of date. it should work now.

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
@galbramc is there anything specific about macys_VM, reynolds, windows7x64 that might cause them to fail a single test? It's stable on those, but I can't reproduce it, so my best guess is that they have a different version of MOSEK, are running on the same hardware, or something like that. In any event, @mjburton11 the new solar model with QPROP seems like it might be marginal...maybe give it some x0s?

**Comment by bqpd** [comment]
test models please

**Comment by galbramc** [comment]
Yes, some machines have mosek and some mosek 8

**Pull request merged**
