### PR TITLE
no units in keydicts

### LINKED ISSUE #1265: error with united substitutions
per https://github.com/convexengineering/heatexchanger/commit/1d5002a5a60f9117d4dc6b868a46001a7a179a74#commitcomment-27637342

### LINKED ISSUE #1267: issue with relaxed_constants for variable matrices
this is generated by running layer.py within commit 01cc73d8d87 of the cfmodel branch of heatexchanger.

```python
In [1]: run layer
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
C:\Users\Berk\Dropbox (MIT)\MIT Graduate School\code\heatexchanger\heatexchanger\layer.py in <module>()
    104     m.substitutions.update()
    105     m.cost = 1/m.Q + m.waterpipes.D.sum()*units('1/(N*W)')+m.airpipes.D.sum()*units('1/(N*W)')
--> 106     m = relaxed_constants(m)
    107     sol = m.localsolve(verbosity=4)
    108     print sol(m.Q)

C:\Users\Berk\Dropbox (MIT)\MIT Graduate School\code\heatexchanger\heatexchanger\relaxed_constants.pyc in relaxed_constants(model, include_only, exclude)
     21
     22     if model.substitutions:
---> 23         constsrelaxed = ConstantsRelaxed(model, include_only, exclude)
     24         feas = Model(constsrelaxed.relaxvars.prod()**20 * model.cost + model.cost,
     25                      constsrelaxed)

c:\users\berk\dropbox (mit)\mit graduate school\code\gpkit\gpkit\constraints\relax.pyc in __init__(self, constraints, include_only, exclude)
    130             relaxvar = Variable(**descr)
    131             relaxvars.append(relaxvar)
--> 132             del substitutions[key]
    133             var = Variable(**key.descr)
    134             # TODO: make it easier to make copies of a variable

c:\users\berk\dropbox (mit)\mit graduate school\code\gpkit\gpkit\keydict.pyc in __delitem__(self, key)
    200             delete = True
    201             if idx:
--> 202                 dict.__getitem__(self, k)[idx] = np.nan
    203                 if not isnan(dict.__getitem__(self, k)).all():
    204                     delete = False

C:\Users\Berk\Anaconda2\lib\site-packages\pint\quantity.pyc in __setitem__(self, key, value)
   1121         try:
   1122             if math.isnan(value):
-> 1123                 self._magnitude[key] = value
   1124                 return
   1125         except (TypeError, DimensionalityError):

IndexError: too many indices for array
```

I wanted to chop the issues related to matrix variables because they may be separate bugs.

### PR DESCRIPTION
**Pull request by bqpd**
closes #1265 
closes #1267

### CODE REVIEW

**Comment by 1ozturkbe** [comment]
yes it does (using Bounded) but there doesn't seem to be an error. Here is the error message: 
```python
In [1]: run layer
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
C:\Users\Berk\Dropbox (MIT)\MIT Graduate School\code\heatexchanger\heatexchanger\layer.py in <module>()
    104     m.substitutions.update()
    105     m.cost = 1/m.Q + m.waterpipes.D.sum()*units('1/(N*W)')+m.airpipes.D.sum()*units('1/(N*W)')
--> 106     m = Model(m.cost,Bounded(m))
    107     sol = m.localsolve(verbosity=4)
    108     print sol(m.Q)

c:\users\berk\dropbox (mit)\mit graduate school\code\gpkit\gpkit\constraints\bounded.pyc in __init__(self, constraints, verbosity, eps, lower, upper)
     70         self.lowerbound = lower if (lower or upper) else eps
     71         self.upperbound = upper if (lower or upper) else 1/eps
---> 72         self.bounded_varkeys = tuple(vk for vk in constraints.varkeys
     73                                      if vk not in constraints.substitutions)
     74         bounding_constraints = varkey_bounds(self.bounded_varkeys,

c:\users\berk\dropbox (mit)\mit graduate school\code\gpkit\gpkit\constraints\bounded.pyc in <genexpr>((vk,))
     71         self.upperbound = upper if (lower or upper) else 1/eps
     72         self.bounded_varkeys = tuple(vk for vk in constraints.varkeys
---> 73                                      if vk not in constraints.substitutions)
     74         bounding_constraints = varkey_bounds(self.bounded_varkeys,
     75                                              self.lowerbound, self.upperbound)

c:\users\berk\dropbox (mit)\mit graduate school\code\gpkit\gpkit\keydict.py in __contains__(self, key)
    126                                          " for value %s" %
    127                                          (key, idx,
--> 128                                           dict.__getitem__(self, key)))
    129                 except TypeError:
    130                     raise TypeError("%s has an idx, but its value in this"

IndexError: key T_in_Layer/RectangularPipe.1 with idx (4,) is out of bounds for value 500 kelvin
```
But the substitution in question seems to be correct (since T_in is a scalar variable that is being vectorized):
```python
        air = Air()
        with Vectorize(Nairpipes):
            airpipes = RectangularPipe(Nwaterpipes, air, increasingT=True,
                                       substitutions={"T_in": 303*units('K'),
                                                      "v_in": 20*units('m/s')})
```
This PR also has no effect on relaxed_constants issue.

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
@mjburton11 @1ozturkbe @pgkirsch this PR changes it so that solutions are stored as magnitudes by default, but the `sol(key)` notation units values before returning them.

This is faster, and my hope is that it'll be more convenient for the cases where you don't want units...is that true, or should I also apply units on a call to `["variables"]`, etc?

**Comment by bqpd** [comment]
test models please

**Comment by pgkirsch** [comment]
@bqpd Can you clarify a little bit? Does this change the behaviour of `sol("variable")`? What returns a magnitude and what returns a unit-ed quantity?

**Comment by bqpd** [comment]
It does not change the behaviour of `sol()`, which will still return united quantities, but `sol[]` will now return floats that are implicitly in the dimensions of their key.

**Comment by pgkirsch** [comment]
Ah I see, sounds awesome. So there is no more `sol["freevariables"]` and `sol["constants"]`? If no, how does one access what was formerly `sol["sensitivities"]`?

**Comment by bqpd** [comment]
Oh, no, they're still there! The data structure is the same as before, but instead of storing Quantities it only stores arrays.

**Comment by pgkirsch** [comment]
OK, sorry now I follow. Not sure if this is good rationale, but `mag(sol('variable'))` is still fewer keystrokes than `sol['freevariables']['variable']` so I will probably still use the former but I have no issue with the latter returning a unitless array. Is that what you were asking for feedback on?

**Comment by bqpd** [comment]
yup! I'm mostly doing this because it makes the internals cleaner

**Pull request merged**
