### PR TITLE
Fresh install fixes

### PR DESCRIPTION
**Pull request by whoburg**
Fixed several broken links in `installation.rst`.

### CODE REVIEW

**Comment by galbramc** [comment]
test this please

**Comment by whoburg** [comment]
367 new pylint warnings seems surprising...

**Comment by galbramc** [comment]
Looks like pylint has evolved over time, and most of the warnings are related to the newer f-string syntax in python. Your call if it should be fixed or suppressed.

**Comment by bqpd** [comment]
ah the fstrings rear their head! gpkit could def use some modernization.

**Review by bqpd — APPROVED** [review]
links look good, thank you!

**Pull request merged**
