### PR TITLE
fix for variables not in sensitivities

### LINKED ISSUE #1318: Issue with sol.diff
I have been doing some changes in turbofan/berkPlaying to get the sensitivities to calm down a little. I run the following in the turbofan/turbofan folder of the last commit (378e7a631957) of that branch using latest gpkit/master:
```python
run engine_validation
print sol.diff('engine_sols/geq_mixing.sol')
```
I get the following error:
```python
In [43]: print sol.diff('engine_sols/geq_mixing.sol')
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-43-7dd7bf6f0a34> in <module>()
----> 1 print sol.diff('engine_sols/geq_mixing.sol')

c:\users\berk\dropbox (mit)\mit graduate school\code\gpkit\gpkit\solution_array.py in diff(self, sol, min_percent, show_sensitivities, min_senss_delta)
    170                 key: (sol["sensitivities"]["variables"][key]
    171                       - self["sensitivities"]["variables"][key])
--> 172                 for key in selfvars.intersection(solvars)
    173             }
    174

c:\users\berk\dropbox (mit)\mit graduate school\code\gpkit\gpkit\solution_array.py in <dictcomp>((key,))
    170                 key: (sol["sensitivities"]["variables"][key]
    171                       - self["sensitivities"]["variables"][key])
--> 172                 for key in selfvars.intersection(solvars)
    173             }
    174

c:\users\berk\dropbox (mit)\mit graduate school\code\gpkit\gpkit\keydict.pyc in __getitem__(self, key)
    163         if not keys:
    164             del self.keymap[key]  # remove blank entry added due to defaultdict
--> 165             raise KeyError(key)
    166         values = []
    167         for k in keys:

KeyError: \gamma_{air}_Engine/Compressor
```
For some odd reason, this key is in ```selfvars.intersection(solvars)```, but returns a KeyError when calling the values? Odd...

### PR DESCRIPTION
**Pull request by bqpd**
Closes #1318

@1ozturkbe, the issue was that some constants are in the solution array even if they are not in any constraints, but only variables in constraints get sensitivities.

### CODE REVIEW

**Comment by bqpd** [comment]
test models please

**Comment by 1ozturkbe** [comment]
right ofc, good to know for future reference.

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Pull request merged**
