### PR TITLE
Directly modify A matrix during SGP solves

### PR DESCRIPTION
**Pull request by bqpd**
Paves the way for removing `.as_approxlts`, `.as_approxgts`, `mutategp`, `blackbox`, `pineq.as_gpconstr`, `sigeq.as_hmapslt1`, `externalfn`, and other joys. Plus, it's much faster.

(note to self: will that still need a fallback for if the number of variables / etc changes size? maybe what I want to do is generate the GP with just the GP constraints first (but, bound warnings), then add the SPs to the A matrix manually?)

### CODE REVIEW

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test this please

**Comment by whoburg** [comment]
cool!

**Pull request merged**
