### PR TITLE
remove ctyespgen dependency

### PR DESCRIPTION
**Pull request by bqpd**

### CODE REVIEW

**Comment by bqpd** [comment]
test this please

**Comment by galbramc** [comment]
I'm confused. I see failures on all machines still.

**Comment by galbramc** [comment]
Ok I fixed up gpkit_install to attempt to run the tests with the respective solver just once. Now it errors out correctly due to the updated ctypesgen.

**Comment by bqpd** [comment]
test this please

**Comment by galbramc** [comment]
Patience. The computers are chugging along as fast as they can.

**Comment by bqpd** [comment]
test models please

**Comment by galbramc** [comment]
So should I remove all the ```pip install ctypesgen``` from Jenkins? Or should I wait until windoze is fixed?

**Comment by bqpd** [comment]
you can go ahead and do it now.

>

**Pull request merged**
