### PR TITLE
Adding kwargs into Tight

### PR DESCRIPTION
**Pull request by 1ozturkbe**
Hey @bqpd, this is partly about issue #1386. I decided that the use cases of Tight are so unique that users will need to figure out their own ways of dealing with it. My way for the solid rocket motor branch (soromotoropt) is to have kwargs to label Tight constraints. This PR just adds the kwargs so I don't have to work out of a branch other than master.

### CODE REVIEW

**Comment by 1ozturkbe** [comment]
If you are good with this, merge, and then close issue #1386.

**Comment by 1ozturkbe** [comment]
@bqpd this is a two minute review. Would really appreciate it!

**Comment by bqpd** [comment]
Sure thing! Labels specifically sound like a great idea, though; would you be interested in making a version that only adds the labeling functionality?

**Comment by 1ozturkbe** [comment]
I debated doing that, but I think it is better to use kwargs for multiple indexing. There may be reasons why you might want multiple attributes on a Tight constraint (eg. you want to validate the constraint for certain kinds of studies).

**Comment by bqpd** [comment]
sounds good to me, I'll merge back at my comp

**Pull request merged**
