### PR TITLE
Ordered printing

### PR DESCRIPTION
**Pull request by bqpd**

### CODE REVIEW

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test this please

**Comment by bqpd** [comment]
test this please

**Comment by bqpd** [comment]
test models please

**Comment by whoburg** [comment]
Is the title still accurate? Add description of changes in this PR?

**Comment by bqpd** [comment]
It does some other things as well (though that's the most of it); I'll definitely put a full description in the commit message!

**Comment by bqpd** [comment]
- ordered printing
- new printing conventions (model.submodel.variable, variable[index])
  - exclude unnecessary lineage in constraint and table printing
  - print full list of constraints for named models
- faster gp.gen()
- use unicode strings and literals
- python 3 consistent ordering fixes
- faster x0 generation for SPs
- faster algebra via pint operation caching

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
test models please

**Pull request merged**
